# Site settings
title: Ryan's blog
header-img: img/home-bg.jpg
email: ryan.w.li@github.io
copyright_name: Ryanwli
description: "clean code, clean life"
baseurl: ""
url: "http://ryanwli.github.io"
twitter_username: ryanwli
github_username:  ryanwli
facebook_username:  ryanwli
email_username:  ryan.w.li@qq.com
future: true
timezone: Asia/Hong_Kong

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
